name: PR checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  static-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: ruff check .
    - run: ruff format --diff .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - uses: pavelzw/pytest-action@v2
      with:
        emoji: false
        verbose: false
        job-summary: true
